"""
Game balancing values (knobs you can tweak easily).
"""

# === PLAYER CONFIG ===
PLAYER_MAX_HP = 3
PLAYER_SPEED = 5
PLAYER_JUMP_FORCE = 15
PLAYER_FIREBALL_LIMIT = 3
COYOTE_TIME = 0.1
JUMP_BUFFER_TIME = 0.1

# === ENEMY CONFIG ===
ENEMY_SPEED = 2
ENEMY_SIZE = (40, 40)
FLYING_ENEMY_SPEED = 2
FLYING_VERTICAL_RANGE = 50

# === BOSS CONFIG ===
BOSS_HP = 5
BOSS_SPEED = 2
BOSS_TURN_DELAY = 140   # 1 second at 60fps
BOSS_ATTACK_COOLDOWN = 60
BOSS_SIZE = (80, 80)

# === FIREBALL CONFIG ===
FIREBALL_SPEED = 8
FIREBALL_MAX_DIST = 500
FIREBALL_COOLDOWN = 10

# === LEVEL CONFIG ===
COIN_ANIM_LIFE = 30
COIN_ANIM_SPEED = 2
DOOR_WIDTH = 60
DOOR_HEIGHT = 70 